# Default title for seo-tag
title: Korde
# Default description in social shares for the jekyll-seo-tag gem
description: Korde er et lite konsulentselskap som utvikler IT-løsninger.  I dag skaper og utvikler vi produkter for etablerte selskaper, og startups med en gode ideer.
url: "https://korde.no"
logo: /images/korde-black.png
google_analytics_key: UA-92595165-1
google_maps_javascript_api_key: AIzaSyD9ZM1iNycbphp1imOJgWeCzyMVnKN0w9I
disqus_shortname: korde

twitter:
  username: Korde_AS

facebook:
  app_id: 1092232697485924

# Social details for the jekyll-seo-tag gem
social:
  name: Korde AS
  links:
    - https://twitter.com/korde_as
    - https://www.facebook.com/kordedigital/
    - https://www.linkedin.com/company/korde
    - https://www.instagram.com/korde_as

collections:
  staff_members:
    output: false
  clients:
    output: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

jekyll-archives:
  enabled:
    - "categories"
  permalinks:
    categories: '/category/:name/'

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "clients"
    values:
      layout: "client"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
